### ISSUE TITLE
Identify and implement tests for deserialization edge cases

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/libzkchannels-crypto#105]
Someone with a cryptographic background should think about weird edge cases for all our cryptographic objects that get deserialized and make sure that they are rejected. (e.g. by writing tests for them).

This should test the properties that are implemented in #92

**Comment by indomitableSwan** [comment]
List:
- [ ] PS sigs:
- - [ ] Secret Key
- - [ ] Public Key
- - [ ] Signature
- [ ] Pedersen commitments
- - [ ] Commitment
- - [ ] Pedersen Parameters
- [ ] Proofs
- - [ ] RangeConstraintParameters (?????)

I think the other structs inherit their (de)serialization.

**Comment by indomitableSwan** [comment]
Closing as too vague.
