### ISSUE TITLE
Expose methods from zkAbacus to check whether building a pay proof *would* succeed

### ISSUE THREAD

**Issue by kwf** [boltlabs-inc/libzkchannels-crypto#126]
Currently in zeekoe, the merchant may approve a payment that cannot be made on a given channel, because the requested payment amount is out of bounds for the channel balances. This presents a minor UX issue, whereby the payment is attempted over the network when it could be pre-emptively rejected, and also by the same token a more major privacy compromise, where the merchant can learn the amount of payments that fail to produce a valid pay proof.

Suggested solution: zkAbacus could provide a method `validate_payment` on the `Ready` struct:

```rust
impl Ready {
    validate_payment(&self, payment_amount: &PaymentAmount) -> bool { ... }
}
```

This method would encapsulate the *validation logic* that occurs prior to the construction of the pay proof that is done in `Ready::start`, but *not* the pay proof creation itself. We would run this method in zeekoe prior to even contacting the merchant to pre-emptively reject payments that are impossible on the given channel.

**Comment by marsella** [comment]
After a conversation with @yaymukund and @indomitableSwan, we decided that this issue is better handled by improved error checking in zeekoe, rather than additional validation in zkAbacus. The updated solution is in boltlabs-inc/zeekoe#334; closing this issue.
