### ISSUE TITLE
Limit accessibility and improve naming on keys

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/libzkchannels-crypto#148]
Make `PublicKey` elements access-only (right now they are all pub, and could be changed arbitrarily).

Consider renaming key elements to something more descriptive:

> if we're trying to improve naming, we might consider more descriptive names for the generators from G. e.g. we have something like message_generators and a blinding_factor_generator.

> we could name these public key bits with respect to the "signature space" and the "verification space".

Also, make sure everywhere that uses a `KeyPair` calls it either `kp` or `signing_keypair`. Some places still use `signing_key`, which is not quite right.

**Comment by gijsvl** [comment]
Make sure that everything also still works in zeekoe (after making fields private)
