### ISSUE TITLE
Improve range proof parameters emperically

### ISSUE THREAD

**Issue by gijsvl** [boltlabs-inc/libzkchannels-crypto#177]
Write some tests to check concrete efficiency of range proofs including deserializing from database. Figure out a balance in parameters that practically works best.

**Comment by indomitableSwan** [comment]
So the first time a party receives the range proof parameters, it makes sense to check that these parameters are well-formed, I think. But after that point, shouldn't we just remember that we have checked them already?

i.e., would it make sense to be storing the parameters as a verified type instead? And then we wouldn't really be losing anything, would we? @gijsvl

**Comment by indomitableSwan** [comment]
> @indomitableSwan After some testing, deserializing takes indeed about 5.5s on my machine, this is mainly due to the verification that we've added, i.e. verifying every signature in the params during deserialization. Removing this brings that number down to roughly 1.3s. Different params bring that down to 130ms, but it increases the actual creating proof and verifying proof by more than 1.3s. Therefore, I think it is best to remove the verification, i.e. signatures are still verified not to have the identity element, but are not validated to be correctly verifying, I don't think this introduces any issues, as a broken signature will just result in a broken range proof. But I leave the final decision up to you.
> 
> Here are the numbers using two different parameter sets (2^63 isn't very easy to split in something else) the current parameters are u=128,l=9. First line shows the time without deserializing the range proof parameters, second line shows with deserialization but without the verification of all the signatures, finally, the last line shows with this verification. Numbers are all in seconds for proof creation and proof verification. Let me know if this is unclear:
> 
> ```
> |                                | u=8, l=21                  | u=128, l=9                 |
> |--------------------------------|----------------------------|----------------------------|
> | without deserialize            | create: 3.4s, verify: 2.9s | create: 1.6s, verify: 1.4s |
> | without signature verification | create: 3.6s, verify: 3.0s | create: 2.9s, verify: 2.6s |
> | with signature verification    | create: 3.9s, verify: 3.4s | create: 7.5s, verify: 7.1s |
> ```
> 
> So choices are:
> 
> * we keep current params and remove signature verification on deserialization
> * we change params and keep signature verification on deserialization.

I'll also note that I don't think we necessarily want to stick with the choice of 2^63 here. e.g. zcash would want 2^64.

**Comment by marsella** [comment]
A type is only verified if you verify it each time you create it (by deserializing or making from scratch). Each time we pull them out of the database, we're deserializing; we haven't explicitly stated our assumptions about who can access and modify the database, but the current architecture ensures that the parameters are valid, at least, at all times.

We could separate validation from deserialization and call it separately at the time we acquire the parameters, but I don't want to make a `ValidatedRangeParameters` type if we're not going to validate it every time.

**Comment by gijsvl** [comment]
Remove validation from deserialization, but add verification when parameters are received from the merchant.

**Comment by gijsvl** [comment]
I've also created a PR on zeekoe to do the actual validation, I think it becomes the right place as zeekoe is kind of responsible for doing input validation in the first place.

**Comment by indomitableSwan** [comment]
> I've also created a PR on zeekoe to do the actual validation, I think it becomes the right place as zeekoe is kind of responsible for doing input validation in the first place.

Can you link to the PR? I don't see it. Wrt to the PR, do you mean we'll provide a validation function in zkAbacus that zeekoe can then call?

**Comment by marsella** [comment]
Yes, that's correct. This PR on zkAbacus moves the validation from the deserialization to a separate, public function: 
https://github.com/boltlabs-inc/libzkchannels-crypto/pull/186

And this PR on zeekoe calls that function in the `get_parameters` protocol:
https://github.com/boltlabs-inc/zeekoe/pull/315
