### ISSUE TITLE
Compare FindoraNetwork implementation to ours

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/libzkchannels-crypto#180]
Is it well written?

Can we use it as a reference implementation?

Do they have any testing techniques we can use?

**Comment by indomitableSwan** [comment]
Closing this as the questions are preserved in https://boltlabs.atlassian.net/wiki/spaces/ZKCHAN/pages/1406664705/related+implementations and I'm not sure it's that useful to track this as a repository issue.
