### ISSUE TITLE
include revocation commitment params in challenge builder

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/libzkchannels-crypto#194]
The generators used in the formation of the revocation lock commitment should be included in generating the challenge.

https://github.com/boltlabs-inc/libzkchannels-crypto/blob/e290b53184f16078fa079a62db2e15ef2753ade2/zkabacus-crypto/src/proofs.rs#L423

**Comment by marsella** [comment]
This will be fixed by #190!
