### ISSUE TITLE
Evaluate tests for serialization of BLS12-381 elements

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/libzkchannels-crypto#29]
At some point, we should examine the existing tests for the BLS12-381 serialization (and for our own serialization wrapper) and determine if we need to add additional testing or fuzzing on top of it. The goal is to make sure there are no edge cases where the G1, G2, and Scalar types can be holding invalid values (e.g. elements not in the group/field).

Here is their [test suite](https://github.com/zkcrypto/bls12_381/blob/main/src/tests/mod.rs).

Here are our existing [audit notes](https://boltlabs.atlassian.net/wiki/spaces/ZKCHAN/pages/956039169/Audit%2BRust%2BBLS12%2Bcurve).

**Comment by indomitableSwan** [comment]
Some observations on the bls12-381 crate:

1. I'm not sure how the test vectors were generated; it's not discussed in the readme or the original commit message.
2. The test vectors include 0, P, 2P, ..., 1000P for the crate's default generator P of the group in question.
3. There aren't specific tests for:
   a. checking that the most-significant three bits are set and interpreted properly as discussed [here](https://docs.rs/bls12_381/0.4.0/bls12_381/notes/serialization/index.html). This includes things like checking that negations of points are encoded as expected.
   b. Failing cases (attempts to deserialize a point not on the curve, a point not in the correct subgroup, or an encoding that has an incorrect setting of one of the most-significant three bits).

**Comment by indomitableSwan** [comment]
Next steps: We might consider taking advantage of the bls12-381 use of the MIT license to borrow their macro and adjust to our testing needs. I think we want similar tests, plus probably checks outlined in #3 above.

**Comment by indomitableSwan** [comment]
Closing as too vague.
