### ISSUE TITLE
Look at RustCrypto signature schemes and their test suites.

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/libzkchannels-crypto#34]
RustCrypto is an intentionally-designed, popular cryptography library. We want to write code to the same standard as them. So, we should audit their tests and see if they use any techniques that we don't yet. Some questions:

- [ ] How do they use random number generators (seeded vs random)
- [ ] Do they test things repeatedly? E.g. many random sigs?
- [ ] Do they use test vectors?
- [ ] Do they use other techniques?

Answers to these (and other) questions should be written here or in a Confluence doc (e.g. next to the BLS12 audit doc).

**Comment by indomitableSwan** [comment]
Closing as too broad.
