### ISSUE TITLE
assess combinatorial trick for CCs range proofs

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/libzkchannels-crypto#6]
Chaabouni R., Lipmaa H., Shelat A. (2010) Additive Combinatorics and Discrete Logarithm Based Range Protocols. In: Steinfeld R., Hawkes P. (eds) Information Security and Privacy. ACISP 2010. Lecture Notes in Computer Science, vol 6168. Springer, Berlin, Heidelberg. https://doi.org/10.1007/978-3-642-14081-5_21

Technique for reducing communication and computational complexity of CCs range proofs ('08) by a factor of two.

**Comment by indomitableSwan** [comment]
What do you estimate for the difficulty of implementing this technique? If it's not too much effort, then I think it would be nice, since I don't think we are going to replace the range proofs immediately. But we are going to be considering alternatives in the near-term, just not immediate, future.

**Comment by gijsvl** [comment]
I've implemented this on a branch (range-proof-optimize), I've done some tests and it seems that we don't get any optimization. The speed seems similar and the sizes of the proof are similar as well (for comparable parameters). I might have done a wrong parameter choice, but it's not that we have a lot of possible choices of parameters. I will inspect it once more next week, and we could have a chat about it at some point. (cc: @indomitableSwan )

**Comment by indomitableSwan** [comment]
@gijsvl Do you think we can close this issue at this point?
